"""Core types for AgentHub."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


class PokemonData(BaseModel):
    """Pokemon data for Agent Companion feature."""

    id: int = Field(..., description="Pokemon ID")
    name: str = Field(..., description="Pokemon name")
    ascii: str = Field(..., description="ASCII art representation")
    type: list[str] = Field(default_factory=list, description="Pokemon types")
    abilities: list[str] = Field(default_factory=list, description="Pokemon abilities")
    height: float = Field(default=0.0, description="Pokemon height")
    weight: float = Field(default=0.0, description="Pokemon weight")
    link: str = Field(default="", description="Pokemon database link")

    @field_validator("ascii", mode="before")
    @classmethod
    def _normalize_ascii(cls, v: str | None) -> str:
        if not v:
            return "\n".join([" " * 60] * 24)
        return v


class InitAgentConfig(BaseModel):
    """Configuration for initializing a new agent."""

    name: str | None = Field(
        default=None,
        description="Agent name. If provided, will try to match a Pokemon name. "
        "If not provided or not matched, a random Pokemon is selected."
    )
    personality: str | None = Field(
        default=None,
        description="Agent personality. If provided, used directly. "
        "Otherwise generated by LLM based on Pokemon type/abilities (Skill Layer)."
    )
    identity: str = Field(..., description="Agent's identity description")
    traits: list[str] = Field(default_factory=list, description="Agent's traits")

    @field_validator("name", mode="before")
    @classmethod
    def _validate_name(cls, v: str | None) -> str | None:
        if v is None:
            return None
        if isinstance(v, str):
            v = v.strip()
            if len(v) > 50:
                v = v[:50]
        return v or None

    @field_validator("personality", mode="before")
    @classmethod
    def _validate_personality(cls, v: str | None) -> str | None:
        if v is None:
            return None
        if isinstance(v, str):
            v = v.strip()
            if len(v) > 500:
                v = v[:500]
        return v or None


class InitAgentResult(BaseModel):
    """Result from init-agent skill execution."""

    # Allow 'COMPLETED' as a synonym for 'FINALIZE' to tolerate LLM variance
    phase: Literal["ORIENT", "GENERATE", "FINALIZE", "COMPLETED"] = Field(
        default="FINALIZE", description="Current phase"
    )
    hasChanges: bool = Field(default=True, description="Whether any changes were made")
    inspirationSeed: int | None = Field(
        default=None, description="Random seed for LLM generation"
    )
    agent_name: str | None = Field(
        default=None, description="LLM-generated agent name"
    )
    personality: str | None = Field(
        default=None, description="LLM-generated personality description"
    )
    pokemon_data: PokemonData | None = Field(
        default=None, description="Pokemon data for companion avatar"
    )
    files_written: list[str] = Field(
        default_factory=list, description="List of files written by Skill"
    )
    git_commit: str | None = Field(None, description="Git commit hash")
    # Tolerate extra fields from LLM non-compliance
    status: str | None = Field(default=None)
    notes: list[str] | None = Field(default=None)

    model_config = {"extra": "ignore"}


class Agent(BaseModel):
    """Represents an agent in AgentHub."""

    id: str = Field(..., description="Unique identifier for the agent")
    name: str = Field(..., description="Name of the agent")
    path: Path = Field(..., description="Path to the agent's directory")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    avatar: str | None = Field(default=None, description="Companion avatar (ASCII art or URL)")


class RawTranscriptInput(BaseModel):
    """Input for evolution - raw transcript to be analyzed."""

    id: str = Field(..., description="Unique identifier for this transcript")
    content: str = Field(..., description="The transcript content")
    project_id: str | None = Field(default=None, description="Optional project identifier")
    metadata: dict[str, Any] | None = Field(default=None, description="Optional metadata")


class EvolutionResult(BaseModel):
    """Result from evolution processing."""

    should_record: bool = Field(..., description="Whether content should be recorded")
    form: Literal["skill", "experience", "none"] = Field(..., description="Form of recording")
    confidence: Literal["high", "medium", "low"] = Field(default="medium", description="Confidence level of the decision")
    skill_name: str | None = Field(default=None, description="Name of the skill if forming a skill")
    scope: Literal["universal", "project_specific"] | None = Field(default=None, description="Scope of the recording")
    experience_type: Literal["user", "feedback", "project", "reference"] | None = Field(default=None, description="Experience subtype")
    projects: list[str] | None = Field(default=None, description="Projects this experience belongs to")
    skip_reason: str | None = Field(default=None, description="Reason for skipping if should_record=False")
    content: str | None = Field(default=None, description="Content to record")
    commit_hash: str | None = Field(default=None, description="Git commit hash if changes were committed")

    @field_validator("confidence", mode="before")
    @classmethod
    def _normalize_confidence(cls, v: str) -> str:
        if isinstance(v, str):
            v = v.strip().lower()
            if v not in ("high", "medium", "low"):
                raise ValueError(f"Invalid confidence value: {v!r}. Must be one of: high, medium, low")
        return v

    @field_validator("experience_type", mode="before")
    @classmethod
    def _normalize_experience_type(cls, v: str) -> str:
        if isinstance(v, str):
            v = v.strip().lower()
            if v not in ("user", "feedback", "project", "reference"):
                raise ValueError(f"Invalid experience_type value: {v!r}. Must be one of: user, feedback, project, reference")
        return v

    @field_validator("form")
    @classmethod
    def _check_form_constraints(cls, v: str) -> str:
        return v


class Change(BaseModel):
    """Represents a change from self-evolution."""

    type: Literal["add_skill", "update_skill", "add_experience", "prune"] = Field(..., description="Type of change")
    action: Literal["create", "merge", "delete", "demote", "archive"] | None = Field(default=None, description="Prune action type")
    path: str = Field(..., description="Path where the change was made")
    skill_name: str | None = Field(default=None, description="Skill name if applicable")
    scope: Literal["universal", "project_specific"] | None = Field(default=None, description="Scope of the change")
    experience_type: Literal["user", "feedback", "project", "reference"] | None = Field(default=None, description="Experience subtype if applicable")
    projects: list[str] | None = Field(default=None, description="Projects this change affects")
    content: str | None = Field(default=None, description="Content of the change")
    reason: str | None = Field(default=None, description="Reason for the change")

    @field_validator("action", mode="before")
    @classmethod
    def _normalize_action(cls, v: str | None) -> str | None:
        if isinstance(v, str):
            v = v.strip().lower()
            if v not in ("create", "merge", "delete", "demote", "archive"):
                raise ValueError(f"Invalid action value: {v!r}. Must be one of: create, merge, delete, demote, archive")
        return v

    @field_validator("experience_type", mode="before")
    @classmethod
    def _normalize_experience_type(cls, v: str | None) -> str | None:
        if isinstance(v, str):
            v = v.strip().lower()
            if v not in ("user", "feedback", "project", "reference"):
                raise ValueError(f"Invalid experience_type value: {v!r}. Must be one of: user, feedback, project, reference")
        return v


class SelfEvolutionResult(BaseModel):
    """Result from self-evolution processing."""

    has_changes: bool = Field(..., description="Whether any changes were made")
    changes: list[Change] = Field(default_factory=list, description="List of changes made")


class SkillEvent(BaseModel):
    """Streaming event from skill execution."""

    type: Literal["chunk", "tool_call", "tool_result", "done", "error"] = Field(..., description="Type of event")
    content: str = Field(..., description="Event content")
    tool_name: str | None = Field(default=None, description="Name of the tool if applicable")
    tool_input: dict[str, Any] | None = Field(default=None, description="Tool input if applicable")


class SkillEventType(str, Enum):
    """Enum for skill event types."""

    CHUNK = "chunk"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    DONE = "done"
    ERROR = "error"


class ModelProvider(str, Enum):
    """Supported model providers."""

    ANTHROPIC = "anthropic"
    OPENAI = "openai"


class AgentHubError(Exception):
    """Base exception for AgentHub errors."""

    pass


class LLMError(AgentHubError):
    """Raised when LLM API call fails."""

    pass


class TimeoutError(AgentHubError):
    """Raised when execution times out."""

    pass


class ParseError(AgentHubError):
    """Raised when LLM response parsing fails."""

    pass


class SecurityError(AgentHubError):
    """Raised for security-related errors (path traversal, dangerous commands)."""

    pass


class NotFoundError(AgentHubError):
    """Raised when a requested resource is not found."""

    pass


class ValidationError(AgentHubError):
    """Raised when input validation fails."""

    pass
